<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="camera_tool" params="prefix parent sd *origin">
    <xacro:include filename="$(find acin_support)/urdf/macros.xacro"/>
    <xacro:property name="length" value="0.427"/>
    <xacro:property name="width"  value="0.080"/>
    <xacro:property name="height" value="0.068"/>
    <xacro:property name="mass" value="0.01"/>

    <link name="${prefix}link_0">
      <xacro:visual_mesh filename="package://acin_support/meshes/camera/mounting.dae">
        <origin xyz="0 0 0"/>
      </xacro:visual_mesh>
      <xacro:collision_box size="${0.102+2*sd} ${0.080+2*sd} ${0.102+2*sd}">
        <origin xyz="0 0 0.051"/>
      </xacro:collision_box>
      <inertial>
        <origin xyz="0 0 0.051"/>
        <mass value="0.01"/>
        <inertia ixx="${0.1*(0.080**2+0.102**2)/12}" ixy="0" ixz="0"
                 iyy="${0.1*(0.102**2+0.102**2)/12}" iyz="0"
                 izz="${0.1*(0.102**2+0.080**2)/12}"/>
      </inertial>
    </link>
    <link name="${prefix}link_1">
      <xacro:visual_mesh filename="package://acin_support/meshes/camera/camera.dae">
        <origin xyz="0 0 0"/>
      </xacro:visual_mesh>
      <xacro:collision_box size="${length+2*sd} ${width+2*sd} ${height+2*sd}">
        <origin xyz="0.005 0.025 ${height/2}"/>
      </xacro:collision_box>
      <inertial>
        <origin xyz="0.005 0.025 ${height/2}"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass*( width**2+height**2)/12}" ixy="0" ixz="0"
                 iyy="${mass*(length**2+height**2)/12}" iyz="0"
                 izz="${mass*(length**2+ width**2)/12}"/>
      </inertial>
    </link>
    <link name="sensor_link"/>

    <joint name="${prefix}joint_0" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${prefix}link_0"/>
    </joint>
    <joint name="${prefix}joint_1" type="fixed">
      <origin xyz="0.0185 -0.00035 0.0903" rpy="${pi} 0 ${-pi/2}"/>
      <parent link="${prefix}link_0"/>
      <child link="${prefix}link_1"/>
    </joint>
    <joint name="sensor_joint" type="fixed">
      <!-- Sensor pose according to Photoneo's CAD model -->
      <!--<origin xyz="0.17280 0.04865 0.03260" rpy="${-pi/2} 0 ${11.75*pi/180}"/>
      <parent link="${prefix}link_1"/>-->
      <!-- Sensor pose according to camera calibration -->
      <origin xyz="-0.0288531 -0.1731820 0.0608131" rpy="1.5825099281614061 -0.004777686036830654 -1.5623068917337075"/>
      <parent link="${prefix}link_0"/>
      <child link="sensor_link"/>
    </joint>
    <link name="gazebo_link"/>
    <joint name="gazebo_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 ${-pi/2} ${pi/2}"/>
      <parent link="sensor_link"/>
      <child link="gazebo_link"/>
    </joint>

    <!-- Plugin for simulation in Gazebo -->
    <gazebo reference="gazebo_link">
      <sensor type="depth" name="camera">
        <update_rate>10</update_rate>
        <camera name="head">
          <!-- Parameters for Photoneo MotionCam-3D M -->
          <horizontal_fov>${2*atan(0.862/2/(0.497+0.442))}</horizontal_fov>
          <image>
            <width>1600</width>
            <height>1200</height>
            <format>B8G8R8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>${5}</far>
          </clip>
        </camera>
          <plugin name="camera_controller" filename="libgazebo_ros_depth_camera.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>0</updateRate>
            <cameraName>camera</cameraName>
            <imageTopicName>image_raw</imageTopicName>
            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
            <depthImageTopicName>depth/image_raw</depthImageTopicName>
            <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
            <pointCloudTopicName>gazebo/point_cloud</pointCloudTopicName>
            <frameName>sensor_link</frameName>
            <hackBaseline>0.07</hackBaseline>
            <pointCloudCutoff>0.1</pointCloudCutoff>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
          </plugin>
        </sensor>
    </gazebo>
  </xacro:macro>
</robot>
