# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_joint_1:
    max_position: 2.792526803
    min_position: -2.792526803
    has_velocity_limits: true
    max_velocity: 1.4835
    has_acceleration_limits: true
    max_acceleration: 1.4835
  arm_joint_2:
    max_position: 1.919862177
    min_position: -1.919862177
    has_velocity_limits: true
    max_velocity: 1.4835
    has_acceleration_limits: true
    max_acceleration: 1.4835
  arm_joint_3:
    max_position: 2.792526803
    min_position: -2.792526803
    has_velocity_limits: true
    max_velocity: 1.7453
    has_acceleration_limits: true
    max_acceleration: 1.7453
  arm_joint_4:
    max_position: 1.919862177
    min_position: -1.919862177
    has_velocity_limits: true
    max_velocity: 1.309
    has_acceleration_limits: true
    max_acceleration: 1.309
  arm_joint_5:
    max_position: 2.792526803
    min_position: -2.792526803
    has_velocity_limits: true
    max_velocity: 2.2689
    has_acceleration_limits: true
    max_acceleration: 2.2689
  arm_joint_6:
    max_position: 1.919862177
    min_position: -1.919862177
    has_velocity_limits: true
    max_velocity: 2.3562
    has_acceleration_limits: true
    max_acceleration: 2.3562
  arm_joint_7:
    max_position: 2.879793266
    min_position: -2.879793266
    has_velocity_limits: true
    max_velocity: 2.3562
    has_acceleration_limits: true
    max_acceleration: 2.3562
  base_joint_1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  base_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  table_joint_2:
    has_velocity_limits: true
    max_velocity: 0.036
    has_acceleration_limits: true
    max_acceleration: 0.036
